[FEAT]:Feature/drop down menu in nav bar
bardovec/techmart-ecommerce pull request #16
Opened 2021-10-10 15:28 UTC by Pavlo-Klymchuk

drop down menu in nav bar

2021-10-15 09:48 UTC, daviddubliakov approved these changes

2021-10-17 10:18 UTC, maxim-petrenko requested changes

2021-10-17 10:18 UTC, maxim-petrenko commented on client/src/components/NavBar/NavBar.jsx
> +    }
Вот это обязательно завернуть в useCallback: `const handleCloseMenu = useCallback(() => setAnchorEl(null), [])`

2021-10-17 12:21 UTC, Pavlo-Klymchuk commented on client/src/components/NavBar/NavBar.jsx
> +    }
fixed

2021-10-18 16:13 UTC, maxim-petrenko approved these changes

2021-10-18 16:13 UTC, merged