[FIX]:Fix tests header, footer
bardovec/techmart-ecommerce pull request #44
Opened 2021-11-12 18:55 UTC by Pavlo-Klymchuk

Fix tests header, footer

2021-11-13 14:11 UTC, maxim-petrenko requested changes

2021-11-13 14:11 UTC, maxim-petrenko commented on client/src/components/Header/__tests__/Header.test.jsx
>      })
Понял, что не выделил строки - с 23 по 48.

2021-11-13 14:11 UTC, maxim-petrenko commented on client/src/components/Header/__tests__/Header.test.jsx
> +    it('Input value', () => {
Про названия написал ниже, этот тест всё равно под снос

2021-11-13 14:11 UTC, maxim-petrenko commented on client/src/components/Footer/Footer.jsx
>          <>
```suggestion
        <footer>
```

2021-11-13 14:11 UTC, maxim-petrenko commented on client/src/components/Footer/__tests__/Footer.test.jsx
> +        expect(logo).toBeInTheDocument()
Нет смысла тестировать рендер компонента Лого, ведь он рендерится не по какому-то условию лучше этот тест поменять на просто smoke-тест для ковереджа (про названия тестов написал ниже):
`it('renders (smoke test)', () => {
        render(
            <BrowserRouter>
                <Footer />
            </BrowserRouter>
        )
        const footer = document.getElementByRole('contentInfo'); // или повесить на футер aria-label свой
        expect(footer).toBeDefined()
        `

2021-11-13 14:11 UTC, maxim-petrenko commented on client/src/components/Footer/__tests__/Footer.test.jsx
> +    it('Input value', () => {
Вот этот тест нужно переписать - он тестит не реальное поведение компонента, а то, что задано в тесте - ну то есть тест тестит сам себя - сам написал обработчик, сам повесил, сам нажал, сам проверил, а компонент просто рядом лежал

2021-11-14 17:00 UTC, Pavlo-Klymchuk commented on client/src/components/Header/__tests__/Header.test.jsx
> +        jest.spyOn(Redux, 'useSelector').mockReturnValueOnce({ userInfo: { isMock: true } });
fixed

2021-11-14 17:04 UTC, Pavlo-Klymchuk commented on client/src/components/Header/__tests__/Header.test.jsx
>          )
fixed

2021-11-14 17:05 UTC, Pavlo-Klymchuk commented on client/src/components/Header/__tests__/Header.test.jsx
>      })
fixed

2021-11-14 17:43 UTC, Pavlo-Klymchuk commented on client/src/components/Header/__tests__/Header.test.jsx
> +    it('Change button signin', () => {
fixed

2021-11-14 18:24 UTC, Pavlo-Klymchuk commented on client/src/components/Header/__tests__/Header.test.jsx
> +    it('Change button logout', () => {
fixed

2021-11-14 18:26 UTC, Pavlo-Klymchuk commented on client/src/components/Footer/Footer.jsx
>          <>
fixed

2021-11-14 18:30 UTC, Pavlo-Klymchuk commented on client/src/components/Footer/__tests__/Footer.test.jsx
> +        expect(logo).toBeInTheDocument()
fixed

2021-11-14 19:03 UTC, Pavlo-Klymchuk commented on client/src/components/Footer/__tests__/Footer.test.jsx
> +    it('Input value', () => {
fixed

2021-11-14 19:03 UTC, Pavlo-Klymchuk commented on client/src/components/Header/__tests__/Header.test.jsx
> +    it('Input value', () => {
fixed

2021-11-14 19:04 UTC, Pavlo-Klymchuk commented on client/src/components/Header/__tests__/Header.test.jsx
>              return filteredProducts;
fixed

2021-11-14 19:04 UTC, Pavlo-Klymchuk commented on client/src/components/Header/__tests__/Header.test.jsx
>      })
fixed

2021-11-14 19:34 UTC, maxim-petrenko approved these changes

2021-11-14 21:49 UTC, daviddubliakov approved these changes

2021-11-15 13:13 UTC, merged